= Minimax-Regret
A method for approximate winner determination and an incremental elicitation protocol based on minimax regret.

Code at https://github.com/oliviercailloux/minimax.


== TODO
* +++<del>+++fix space authors+++</del>+++
* Change Table3 according to Figure 2, table 3 divide qv per voter
** 25% PC q_v / #V ; 50% PC q_V / #V ; 75% PC q_v / #V
* Add the example we provided in the rebuttal about the reviewing process of a conference
** Yes in the introduction
* Do we separate again Introduction and Related work?
** No
* Discuss whether the profile asked to the chair could be simplified into "frequency of arrival" (a was ranked 3 times first etc)
** Add a note that point out that we have only 4 possible pref orders and the example if we have space
* Restore the inline formulas?

=== Previous TODO

* Similarity measure for preference rankings and use it as an explanation for the performance of the datasets.

* Rephrase the experimental section writing the hypotesis first
* Using \succeq^p_j(x) to denote the set of alternatives weakly worse than x can be confusing. Please consider using a different notation such as A^(\succeq^p_j,x). 
** https://en.wikipedia.org/wiki/Upper_set[see Upper Set]
* Experiments to elicite the scoring rule when knowing the full profile
** Plot of decresing regret
* Considerations on the distribution of the questions






