= Minimax-Regret
A method for approximate winner determination and an incremental elicitation protocol based on minimax regret.

Code at https://github.com/oliviercailloux/minimax.


== TODO
* Reduce the paper to 6+1 pages
** Put all display math in the text (Olivier)
** Shorten the example for proposition 4 (Olivier)
* Merge (and shorten) introduction and related works (Paolo)
** Add that asking questions to the committee in term of profile is new and must be stressed more. Also, this is compatible with every rule. If we ask about the weights it works only for scoring rules.
* Cover letter
** Add new ID and IJCAI ID (Bea)
** Add rejected ijcai paper (Bea)
** Add table of content (Bea)
* XPs Irish with css (Bea)
* Similarity measure for preference rankings and use it as an explanation for the performance of the datasets.


* Rephrase the experimental section writing the hypotesis first
* Using \succeq^p_j(x) to denote the set of alternatives weakly worse than x can be confusing. Please consider using a different notation such as A^(\succeq^p_j,x). 
** https://en.wikipedia.org/wiki/Upper_set[see Upper Set]
* Experiments to elicite the scoring rule when knowing the full profile
** Plot of decresing regret
* Considerations on the distribution of the questions






