= Minimax-Regret
A method for approximate winner determination and an incremental elicitation protocol based on minimax regret.

Code at https://github.com/oliviercailloux/minimax.


== TODO
* +++<del>+++Add to the paper:+++<del>+++
** +++<del>+++the example written in the rebuttal+++<del>+++
** +++<del>+++that we use similar size for our experiments than the one used in the paper of Oliver & Ulle+++<del>+++
* +++<del>+++Add references proposed by R1 and by Olivier (Sertel 2005)+++<del>+++
* +++<del>+++Correct typos+++<del>+++
* Improve the code
* Rewrite the proof of claim 4 (Olivier)
** R1:  I think that Claim 4 should say something along the lines: "There is a profile P', such that ... and P' can be computed effectively".
* Rephrase the introduction (Paolo)
* Find dataset in preflib
* +++<del>+++Read again the reviews to check we haven't missed anything+++<del>+++
* Reduce the paper to 6+1 pages
* +++<del>+++Ijcaj canvax+++<del>+++
* Figure 1, X axis label should say "Number of questions"
** Also, the labels are not consistent among figures


== To discuss:
* I do not understand why the authors use "Claims" and not "Propositions".
* In several places you use the phrase "permits to" when it might be clearer to say "allows for".
* there are no necessary winners OR there is no necessary winner ?
* "less good than or equal to"-->You could rather say "weakly worse".
* Using \succeq^p_j(x) to denote the set of alternatives weakly worse than x can be confusing. Please consider using a different notation such as A^(\succeq^p_j,x).
* "We see that the number of questions required to reach a low regret level grows approximately linearly with the number of agents"-->Can you provide a formal regression analysis to support this claim?
* "that allows to reproduce our experiments, and more"-->It would be useful to mention the other benefits explicitly.
* "halving the number of questions will only reduce the gain in regret by less than half"-->Might be clearer to say "halving the number of questions reduces the regret by more than 50%".



* Regarding partial preferences and manipulation, one may also look at the following one (although it is less related, for sure):
Dorothea Baumeister, Piotr Faliszewski, Jérôme Lang, Jörg Rothe:
Campaigns for lazy voters: truncated ballots. AAMAS 2012: 577-584

=== Rules for resubmission:
Authors of papers that have been rejected at any peer-reviewed conference within the past 6 months must declare the resubmission by including a cover letter with their submission. The cover letter should summarize the main reasons for rejection and should describe the changes the authors have made to address the reviewers’ comments. The cover letter should be inserted at the beginning of the submitted PDF, along with the previous reviews and previous anonymized rejected submission, before the 6+1 pages of the paper. Such resubmissions must contain, in a single PDF file:

– the cover letter, starting with the title of the rejected paper, the tracking number (if any), and the name of the conference to which this paper was submitted,
– the full reviews from the rejected conference,
– the anonymized version of the rejected paper, and
– the new submission.

A paper rejected from a peer-reviewed conference within the past 6 months  will be rejected without further review if the authors do not declare the resubmission.
