= Minimax-Regret
A method for approximate winner determination and an incremental elicitation protocol based on minimax regret.

Code at https://github.com/oliviercailloux/minimax.


== TODO
* +++<del>+++convert format+++</del>+++
* add back in the text the table about the number of questions asked to chair/agents (Table 1 from Appendix)
** Added, maybe we can add few comments though (p. 10 Evaluation of Pessimistic Strategy)
* add back the proofs for propositions 1,2,4
* add the example we provided in the rebuttal about the reviewing process of a conference
* redo all tables and figures with the new data
* discuss whether the profile asked to the chair could be simplified into "frequency of arrival" (a was ranked 3 times first etc)
* solve issues pointed out in IJCAI reviews
* restore the inline formulas?

=== Previous TODO

* Similarity measure for preference rankings and use it as an explanation for the performance of the datasets.

* Rephrase the experimental section writing the hypotesis first
* Using \succeq^p_j(x) to denote the set of alternatives weakly worse than x can be confusing. Please consider using a different notation such as A^(\succeq^p_j,x). 
** https://en.wikipedia.org/wiki/Upper_set[see Upper Set]
* Experiments to elicite the scoring rule when knowing the full profile
** Plot of decresing regret
* Considerations on the distribution of the questions






